<h1>Attributes</h1>
<a href="{url alias='attribute_add'}"/>
    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAAACXBIWXMAAAbsAAAG7AEedTg1AAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAADlQTFRF////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlx7TAAAABJ0Uk5TAAETJkRocH+Amamztcvm8/b4dwgg7gAAAGZJREFUGJVlzzsWgyAUBNALEiOggm//i02RVGHKOfMF29Hvux+bL9I+n6vW65l7gnRGy5BbnAl7vH5Sr9jZZoNSoM3N8WQYA/Lz1i8QAa7urpQRETEK9V6JxbKELrXLsHX6cu7v/gcH3AWzLpi+OgAAAABJRU5ErkJggga7b7b32f392efc87c0fb2a2fbb4c19d5"/>
    New Attribute
</a>
<br/><br/>
<table>
{foreach from=$categories item=$category}

{/foreach}
</table>